# Copyright The Linux Foundation and each contributor to LFX.
---
site_name: 'LFX One FGA Sync'
site_description: 'Documentation for LFX One FGA Sync'
nav:
  - Home: index.md
plugins:
  - techdocs-core
